fs.jekyll:
  image: tianon/true
  volumes:
    - ./src:/src

fs.sbt:
  image: tianon/true
  volumes:
    - ./src/_site:/usr/share/nginx/html:rw
    - ./nginx-conf:/etc/nginx/conf.d:rw
    - ./nginx-certs:/etc/nginx/ssl:rw
    - ./nginx-logs:/etc/nginx/logs:rw

jekyll:
  image: jekyll/jekyll:3.1.3
  command: bundle exec jekyll build --incremental --watch
  volumes:
    - ./src:/srv/jekyll

sbt:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - fs.sbt


